services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: database
      POSTGRES_PASSWORD: password
      POSTGRES_DB: straysafe
    shm_size: 256mb

  backend:
    build:
      dockerfile: backend/Dockerfile
    ports:
      - 8080:8080
    environment:
      DSN: postgres://database:password@db:5432/straysafe
      JWT_SECRET: hugesecret
    volumes:
      - img:/app/img
    depends_on:
      - db
      - auth

  auth:
    build:
      dockerfile: auth-micro/Dockerfile
    ports:
      - 9876:9876
    depends_on: [db]
    environment:
      DSN: postgres://database:password@db:5432/straysafe
      JWT_SECRET: hugesecret
#    logging:
#      driver: none

  frontend:
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - 8:8081
volumes:
  img:
    name: image-directory